//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VictoryLinkTask.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public int MobileNumber { get; set; }
        public string Action { get; set; }
        public bool Handled { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> HandlingDate { get; set; }
    }
}
